# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
