# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coninfo',
            name='registration_opens',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 5, 0, 29, 56, 878278, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
