# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('con', '0002_coninfo_registration_opens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField()),
                ('payment', models.CharField(choices=[('R', 'Payment Received'), ('C', 'Paying by Cash'), ('Q', 'Chase Quick Pay'), ('P', 'Paying by Venmo'), ('V', 'Paying by Paypal')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='blockregistration',
            name='user',
        ),
        migrations.AddField(
            model_name='blockregistration',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='con.Registration'),
            preserve_default=False,
        ),
    ]
