# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0003_auto_20160305_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 5, 19, 10, 35, 189455, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
