# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0004_registration_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='coninfo',
            name='max_attendees',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
