# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0005_coninfo_max_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.CharField(choices=[('C', 'Paying by Cash'), ('Q', 'Chase Quick Pay'), ('P', 'Paying by Venmo'), ('V', 'Paying by Paypal')], max_length=1),
        ),
    ]
