# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0006_auto_20160305_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockregistration',
            name='time_block',
            field=models.CharField(max_length=64),
        ),
    ]
