# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 00:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0007_auto_20160305_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 6, 0, 9, 18, 412512, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='last_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
