# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 06:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0008_auto_20160306_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('slug', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='con.PaymentOption'),
        ),
    ]
