# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0009_auto_20160309_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='button',
            field=models.TextField(blank=True, null=True),
        ),
    ]
