# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-09 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0002_coninfo_game_reg_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='duration',
            new_name='game_length',
        ),
        migrations.AlterField(
                model_name='game',
                name='game_length',
                field=models.CharField(max_length=64, verbose_name='Game Length'),
        ),
        migrations.AddField(
            model_name='game',
            name='preferred_time',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Preferred Time(s)'),
        ),
        migrations.AddField(
            model_name='game',
            name='special_requests',
            field=models.CharField(blank=True, default='', help_text='(e.g. preferred room)', max_length=256,
                                   verbose_name='Special Request(s)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='number_players',
            field=models.CharField(max_length=32, verbose_name='Number of Players'),
        ),
    ]
