# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-17 03:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0006_referral_admin_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coninfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coninfo',
            name='door_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coninfo',
            name='game_reg_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 16, 1, 0, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='coninfo',
            name='game_sub_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coninfo',
            name='location',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='coninfo',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coninfo',
            name='pre_reg_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coninfo',
            name='pre_reg_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coninfo',
            name='registration_opens',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
