# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-01-17 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convention', '0007_auto_20190117_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='coninfo',
            name='title',
            field=models.CharField(default='Shadowcon 1984', max_length=256),
        ),
        migrations.AddField(
            model_name='game',
            name='convention',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='convention.ConInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='convention',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='convention.ConInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='convention',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='convention.ConInfo'),
            preserve_default=False,
        ),
    ]
